### ISSUE TITLE
Simply remove the `$fun` and `addEta()` would retain whatever it needs to retain

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2lib#31]
Simply remove the `$fun` and it wold retain whatever it needs to retain, actually.  But it would be a full rxode2 ui object (I'm unsure why you only wanted to return the function here).

_Originally posted by @mattfidler in https://github.com/nlmixr2/rxode2/issues/439#issuecomment-1445266844_

**Comment by billdenney** [comment]
@mattfidler , I took a look, and I need to make the model into a function to search and replace within its parse tree: https://github.com/nlmixr2/nlmixr2lib/blob/main/R/searchReplace.R

Is there a way to do that keeping it as an rxode2 object?

**Comment by mattfidler** [comment]
I took a shot at it.  

What to keep may depend on the object as the ecosystem grows.  This will work for any object and will black-list items to carry along, as with our discussion about what should be kept while piping new parameters.
