### ISSUE TITLE
Make eta-detection smarter?

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2lib#38]
@mattfidler, To make eta-detection better, I have selected the first parameter from `.ui$varLhs`:

https://github.com/nlmixr2/nlmixr2lib/blob/71578a7db0dc5190c32743d9dd232f2b0c1b0f05/R/addEta.R#L39-L42

The first parameter from `$varLhs` will usually be what the modeler means to use for the main parameter to add to, but it's not guaranteed to be correct.  Is there a way to get the "this is the parameter (and not a covariate) that has nothing multiplied by it"?  (I'm guessing the answer is "not easily", but it doesn't hurt to ask.)

**Comment by mattfidler** [comment]
To be more clear you are trying to distinguish between a theta that is
estimated and a theta associated with a covariate.

I believe it is there in the ui but since I am answering on my phone I cant
look it up.

**Comment by mattfidler** [comment]
Try `f$covLhs`

``` r
library(rxode2)
#> rxode2 2.0.12.9000 using 8 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`

cmt <- function() {
  ini({
    tka <- 0.45; label("Ka")
    tcl <- 1; label("Cl")
    tv <- 3.45; label("V")
    eta.ka ~ 0.6
    eta.v ~ 0.1
    add.sd <- 0.7
    twt <- 0
  })
  # and a model block with the error specification and model specification
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + wt*twt)
    v <- exp(tv + eta.v)
    d/dt(depot) = -ka * depot
    d/dt(center) = ka * depot - cl / v * center
    cp = center / v
    cp ~ add(add.sd)
  })
}

f <- cmt()

f$covLhs
#>   wt 
#> "cl"
```

<sup>Created on 2023-03-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattfidler** [comment]
Nevermind that isn't quite what is needed.

**Comment by mattfidler** [comment]
I guess the answer is yes it is possible, but currently is not saved.

I think this really probably needs to be part of the ui.  This way it is parsed when already walking the model parsing tree.

**Comment by mattfidler** [comment]
I would suggest deferring this to later.  It seems CRAN is waiting for this for `nlmixr2est`

**Comment by billdenney** [comment]
No worries to wait.  I will submit tomorrow.  I wanted to get the known bugs fixed and to give Justin a nudge to finish his PR.

**Comment by mattfidler** [comment]
This should work.  The `$singleTheta` should be able to marry the ETAs now.

But it needs the next rxode2, I guess.

It is also "blessed" by being a known part of the ui, so it won't be dropped with piping

**Comment by billdenney** [comment]
I think that this is fixed now.
