### ISSUE TITLE
Discussion: Parameter naming conventions

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2lib#4]
> More of a question: When I write my nlmixr2 models, I use different parameter names for the estimated parameter compared to the parameter used in the model (unless they are fully identical). In the current code, some values are reassigned like ka <- exp(ka). I had thought that this would cause issues with either rxode2 or nlmixr2est, but it does not seem to cause problems. @mattfidler , is there a preferred equation format like the above or something like ka <- exp(lka)?

I'm unsure if there is anything that is preferred, except I think that `ka <- exp(ka)` may cause confusion for many PMX people.  I would say stick to some terminology and use it consistently.  

In that direction, some things to consider:
- The `lka` is dependent on transformation.  What would you use for `logit()`/`expit()` or `probit()`/`probitInv()`
- Should it indicate that it is a population parameter (`pop.` as in `assemblerr`)
- Should we indicate between subject variability or simply `eta`?

_Originally posted by @mattfidler in https://github.com/nlmixr2/nlmixr2lib/issues/3#issuecomment-1238331420_

**Comment by billdenney** [comment]
Thoughts up to this point:

1. PK model parameters will have a consistent set of parameter names across 1-, 2-, and 3-compartment models.
2. PD model parameters should also have a consistent set of parameter names when used in different types of models though the parameter itself is related.
3. Indication of transformations are more complex.
4. How should we indicate population parameters vs. random effects (IIV, eta, etc.)?

**Comment by billdenney** [comment]
My opinions:

I think that covering transformations as part of the parameter name will become complicated.  We currently think of `exp()`/`log()`, `logit()`/`expit()`, and `probit()`/`probitInv()`.  We may have more transformations in the future, so I'd like something that is generic and understandable across any transformation.  I would propose one of the following:

1. Prefix the parameter name with the full transform (e.g. `logKa`).  The downside is that the naming gets longer and equations in reports are somewhat less readable (for example `exp(logKa)` looks less readable to me than `exp(lKa)`, but I accept differing opinions here).
2. Given the (great) table layout that `nlmixr2` provides, population parameters are pretty easy to determine from the way that it is printed.  It is less clear within the model code itself, but that is solvable by...
3. If we prefix all random effects with `eta`, then I think that would ensure that population-level effects are clearly differentiated.  And in the table layout, the `eta` doesn't show up in the main table (it would show up in a correlation table below), so it is a smaller impact.

**Comment by mattfidler** [comment]
I prefer including information with the transformation.  I typically prefer smaller names too.  So `lKa` seems fine to me, but for less common transformations `logitF` would make sense.

I think that simply prefixing or post-fixing by `eta.` would be fine.
