### ISSUE TITLE
Add model attributes

### ISSUE THREAD

**Issue by john-harrold** [nlmixr2/nlmixr2lib#69]
It would be useful to have the following attributes included in the model database for each model:

- [x] Dosing states/compartments and expected dosing units.
- [x] Time units of the system (days, weeks, etc or something like NS for not specified).
- [x] A flag indicating if the model is a solved system or defined by ODEs.
- [x] Add a depends field for model piping. E.g., the tumor growth models depend on cp being defined.

**Comment by billdenney** [comment]
Good ideas:

1. Dosing compartments can be implicitly determined by the following rules.  We should be able to write a function to define these rules.  I think that exceptions to the rules would be useful to clarify:
    1. If there is a `depot` compartment, that can be used for extravascular dosing.
    2. If there is no `depot` compartment but there is a `central` compartment, that can be used for intravenous dosing.
    3. If there is a `depot` and `central` compartment and a `f(depot)` term, then both IV and extravascular dosing can be used.
    4. Beyond those, the model would need to specify that.
2. For dosing units and time units, yes, and I would expand this that a general unit definition meta-data structure would be useful.  I think that the easiest way to do that would be:
    1. Create a named character vector called `units` in the meta-data at the top of the model.  Something like `units <- c("amt" = "mg", time = "hr", cl = "L/hr")`, etc.
    2. But, units won't apply to the base models (e.g. the generic 1-compartment model does not have defined units).
3. The flag if the model is a solved system vs ODE I think would also be easiest as a function to detect that.  It could also be a mixed state, I think (both `linCmt()` and ODEs can work, but it is not well tested).

I'd add one more thing that could be useful:  Give typical dosing amounts.  For example, if it is a model for an approved drug, give the approved dose (or one of the approved doses, if there is more than one).

**Comment by john-harrold** [comment]
So there are a couple things here.

One is the specification within rxode2. I do think that @mattfidler should chime in on this. As I understand it, these attributes are kind of free form in the function definition. But I think it would be good to kind of standardize on some of these. So I don't know if it belongs here or if it should be spec'd out in the rxode2 package.

Then the second is how to include this information in the package. I think the rules you outlined for detecting dosing above makes sense. So if it's not an attribute, we can try to figure it out. What I need is for this information to be in the database table somewhere or some structured list. What I'm trying to avoid is building each model to get at these values. 

I bugged Matt and he created the params field of the rxode2 object. So there is a lot of information there. I think the linCmt field could be used to determine if any solved values were being used (see below). What I need to know is if it's being used at all. So like a linCmt column in the modeldb dataset that is being export would be useful.

I can try and implement some of this and submit a pull request once we figure the details.

```r
library(nlmixr2lib)
source(system.file(package="nlmixr2lib","modeldb", "PK_1cmt.R"))
obj = rxode2(PK_1cmt)
obj$params$linCmt
```

**Comment by john-harrold** [comment]
I'm working on a pull request and creating the documentation. I have a question. This says that the concentration in the central compartment should be `cp`:

https://nlmixr2.github.io/nlmixr2lib/articles/create-model-library.html#estimated-parameter-naming

But the examples I've looked through seem to be using `Cc`, see here for an example:

https://github.com/nlmixr2/nlmixr2lib/blob/b8b864636b323df72b5cc7aa318694a72bc1589e/inst/modeldb/PK_1cmt_des.R#L19

I think this needs to be changed in the documentation right?

**Comment by billdenney** [comment]
Yeah, it should change in the documentation.  Thanks for finding that.

**Comment by john-harrold** [comment]
I submitted a pull request: https://github.com/nlmixr2/nlmixr2lib/pull/73

**Comment by mattfidler** [comment]
> One is the specification within rxode2. I do think that @mattfidler should chime in on this. As I understand it, these attributes are kind of free form in the function definition. But I think it would be good to kind of standardize on some of these. So I don't know if it belongs here or if it should be spec'd out in the rxode2 package.

It only belongs in rxode2 if it needs special handling when printing (like `omega` and `thetaMat` for instance.  All options in the rxode2 model are passed to the `rxSolve` though this can be a bit confusing if trying to use the same function for estimation.
